version: "3.3"

services:
  app:
    image: quimbu/squit-backend
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - 4000:4000
    depends_on:
      - "db"
  db:
    image: mariadb:10.4.10
    environment:
      MYSQL_ROOT_PASSWORD: Mambo94
      MYSQL_DATABASE: test
      MYSQL_USER: root
      MYSQL_PASSWORD: Mambo94
    ports:
      - 3307:3307